### ISSUE TITLE
Sort out UiView/grain data model confusion

### ISSUE THREAD

**Issue by zenhack** [zenhack/tempest#16]
As I go to implement sharing links, some oddities with Sandstorm's data model around grains vs. UiViews are rearing their heads, and it seems worth thinking about a proper resolution to these now, rather than just keep fudging it. Definitions:

- A grain is a sandboxed instance of an app, with it's own mutable storage.
- A UiView is the capnp interface defined in grain.capnp, which is the entry point for interacting with a grain view the UI. Every grain has one of these that it provides on startup, but in principle a UiView doesn't need to be the root UiView for a grain; a grain could provide other, secondary UiViews. For example, Davros could grow a feature where you can share a subdirectory via the powerbox, and then recipients could open up just that folder in the normal Davros UI. For that matter, there's no reason a UiView should need to be backed by anything in particular, as long as it implements the interface correctly.

However, Sandstorm does not currently support anything other than a grain's root UiView showing up in the user's grain list, and I'm not sure if it's actually possible to open a non-grain-root UiView at all (I suspect not).

There is at least one weirdness that Tempest carries over from Sandstorm that would need to be addressed to properly decouple these, namely that grain ids show up in various places in the UI & frontend code, mainly the URLs (/grain/<grain-id>). Probably we want to change this, but that leaves some UI questions to be resolved:

- Do UiViews that users have access to have stable URLs/identfiiers still?
  - If so, are they the same for different users? 
  - If not, how should URLs work for these?

From a capability architecture standpoint, it seems like these shouldn't have global names, they should just be reference's hanging off the user's grain list (which I've been calling a 'keyring' in the code, since it's basically a collection of capabilities...).

@ocdtrekkie, interested to hear your thoughts on the UX side of this.

**Comment by ocdtrekkie** [comment]
I *feel* like this is looking for increased complexity. Would the goal here to provide a more granular sharing unit than a grain, in your Davros example?

**Comment by zenhack** [comment]
Kinda, yeah. What I'm describing was I intended for Sandstorm at some point, I'm just wanting to fuss with it now because we're already in this weird confusing state with what the database schema should look like, and it doesn't seem worth living with that longer than we have to.

**Comment by ocdtrekkie** [comment]
I tend to think of the grain as the security boundary, and I think that generally makes app development easier. I think I'd probably rather focus on making ways to compose grains more intelligently (and maybe obscure ones people don't need direct visibility to in the grain list), rather than try to subdivide grains.

**Comment by zenhack** [comment]
Thinking about this, I think not having stable URLs at least at per-user for UiViews (whether or not we can have more than one per grain) would be a very bad UX. It means not being able to bookmark things for one. In any case, I think I can rig this up so that in the case of a grain's root UiView, the URL is always based on the grain ID, while for non-root UiViews it could be different.

I probably won't implement everything necessary for non-root UiViews, but right now it's already implied API (carried over from sandstorm) and *half* in the data model, and I just want internals that are coherent.

**Comment by zenhack** [comment]
(Note that a lot of the questions around "but the grain is the security boundary" are going to need to be dealt with in some way when we get into seriously using the powerbox; exporting individual objects from within a grain is something that it lets you do in general, and it isn't specific to UiViews).

**Comment by zenhack** [comment]
I'm going to close this; I think I have a model I like well enough for the time being.
