### ISSUE TITLE
Document where to get bpf_asm on common distros.

### ISSUE THREAD

**Issue by zenhack** [zenhack/tempest#2]
I just added a seccomp filter to the sandbox setup code, which introduces a build dependency on `bpf_asm`. We should document how to get this on various distros, and also update the Vagrantfile to fetch it automatically. The package is called `bpf` on Archlinux, but I haven't found one for it in Fedora yet.

**Comment by ocdtrekkie** [comment]
Is there a good reason not to grab it from https://github.com/cloudflare/bpftools ? If we are eventually planning to make an install process for Tempest, it may be worth avoiding really annoying distro-specific choices.

I've spent about a half hour trying to find it for Fedora.

**Comment by zenhack** [comment]
I'd rather not pull in the cloudfare version; it hasn't been updated in many years, and thus is missing some fixes that would have saved me a lot of time if I was using a newer version when developing the filter. We could just do what we did in Sandstorm and pulling it into our source tree directly.

It's possible it just *isn't* packaged in Fedora. It's really kindof annoying that this trivial little tool is buried inside one of the largest public git repositories there is...

**Comment by zenhack** [comment]
Tbh, I have a might mild preference for trying to get it packaged in distros where it isn't rather just bundling it.

**Comment by zenhack** [comment]
I added some instructions to the README on installing bpf_asm from source, calling this good (but wouldn't mind feedback on the docs).

**Comment by ocdtrekkie** [comment]
Seems reasonable, assuming I can easily find those two other dependencies on the package manager. Awesome. Re: the outstanding Go issue... as per nearly every other place we use Go, we probably should get the latest version from upstream rather than depend on distros having a currentish version, probably.

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2023-05-02 00:05:45)

> Seems reasonable, assuming I can easily find those two other
> dependencies on the package manager. Awesome.

Yeah, these are extremely standard packages.

> Re: the outstanding Go issue... as per nearly every other place we use
> Go, we probably should get the latest version from upstream rather
> than depend on distros having a currentish version, probably.

Frankly, 1.19 is pretty recent -- it's one release out of date, which so
is Fedora 37, so probably we should just bump to Fedora 38 before we
fuss with anything else.

**Comment by zenhack** [comment]
Ok, yeah, I updated the vagrant file to fedora 38, which ships Go 1.20, and that works now.
