### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by zenhack** [zenhack/tempest#9]
Tempest needs to support HTTPS, ideally with automatic configuration via ACME/Let's Encrypt

**Comment by zenhack** [comment]
Will probably use https://go-acme.github.io/lego/ for ACME support

**Comment by ocdtrekkie** [comment]
Looks like a really healthy supported DNS provider list.

**Comment by zenhack** [comment]
Yeah. I noticed that. Like, wow.

**Comment by zenhack** [comment]
HTTPS is working, ACME support is still WIP

**Comment by zenhack** [comment]
Opened a separate issue (#12) for acme; closing this one.
